base_url = "https://jliu.xyz"

title = "James Liu"
default_language = "en"

compile_sass = true
build_search_index = true
minifiy_html = true

generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true

[extra]
site_name = "James Liu"
