# On every push this script is executed
on: [push, workflow_dispatch]
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Mark repo as safe directory
        run: git config --global --add safe.directory /github/workspace/sass/vendor/bulma
      - name: build_and_deploy
        uses: james7132/zola-deploy-action@patch-2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
